CONNECT TO DESAFIO;

-- CLIENTE: valida CPF como 11 dígitos numéricos
ALTER TABLE CLIENTE
  ADD CONSTRAINT CK_CLIENTE_CPF_FMT
  CHECK (CPF BETWEEN '00000000000' AND '99999999999');

-- CPF já era UNIQUE, mas reforçamos com índice explícito
CREATE UNIQUE INDEX UQ_CLIENTE_CPF ON CLIENTE (CPF);


-- Índice composto em agência + número
CREATE UNIQUE INDEX UQ_CONTA_AGENCIA_NUMERO ON CONTA(AGENCIA, NUMERO);

-- Check constraint para garantir apenas 'CREDITO' ou 'DEBITO'
ALTER TABLE TRANSACAO
  ADD CONSTRAINT CK_TRANSACAO_TIPO
  CHECK (TIPO IN ('CREDITO','DEBITO'));
