CONNECT TO DESAFIO;

-- Índices direcionados às consultas
CREATE INDEX IX_CONTA_CLIENTE           ON CONTA (CLIENTE_ID);
CREATE INDEX IX_TRANSACAO_CONTA_DATA    ON TRANSACAO (CONTA_ID, DATA);


-- Estatísticas para o otimizador (recomendado após carga/índices)
RUNSTATS ON TABLE CLIENTE   WITH DISTRIBUTION ON ALL COLUMNS AND SAMPLED DETAILED INDEXES ALL;
RUNSTATS ON TABLE CONTA     WITH DISTRIBUTION ON ALL COLUMNS AND SAMPLED DETAILED INDEXES ALL;
RUNSTATS ON TABLE TRANSACAO WITH DISTRIBUTION ON ALL COLUMNS AND SAMPLED DETAILED INDEXES ALL;
