-- Estrutura inicial de tabelas DB2 (ajustada para compatibilidade)

CREATE TABLE CLIENTE (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    CPF CHAR(11) UNIQUE NOT NULL,
    DATA_CADASTRO DATE NOT NULL
);

CREATE TABLE CONTA (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CLIENTE_ID INT NOT NULL,
    AGENCIA VARCHAR(10),
    NUMERO VARCHAR(20) NOT NULL UNIQUE,
    SALDO DECIMAL(15,2) DEFAULT 0,
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID)
);

CREATE TABLE TRANSACAO (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CONTA_ID INT NOT NULL,
    DATA TIMESTAMP NOT NULL,
    TIPO VARCHAR(10) CHECK (TIPO IN ('CREDITO','DEBITO')),
    VALOR DECIMAL(15,2) NOT NULL,
    FOREIGN KEY (CONTA_ID) REFERENCES CONTA(ID)
);
